TARGET = 'TouchMovieApp'

SOURCES = ['TouchMovieApp.cpp', 'Area.cpp', 'AreaController.cpp',
		'Movie.cpp']
ASSETS = ['data.xml', 'bg_01.mov', 'rollover_01.mov']

DEBUG = 0

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'ASSETS', 'DEBUG'])

