TARGET = 'TouchMovieApp'

SOURCES = ['TouchMovieApp.cpp', 'Area.cpp', 'AreaController.cpp',
		'Background.cpp', 'Movie.cpp', 'PParams.cpp', 'KinectUser.cpp']
ASSETS = ['data.xml', 'back.jpg', 'bg_01.mov', 'rollover_01.mov']
RESOURCES = ['line.vert', 'line.frag', 'line.geom']

DEBUG = 0

CINDERNIPATH = '../../../blocks/Cinder-NI/scons/'

import sys
sys.path.append(CINDERNIPATH)
import CinderNI
SOURCES += CinderNI.getSources(CINDERNIPATH)
INCLUDES = CinderNI.getIncludes(CINDERNIPATH)
LIBS = CinderNI.getLibs(CINDERNIPATH)
LIBPATH = CinderNI.getLibPath(CINDERNIPATH)

CINDER_OPENCV_PATH = '../../../blocks/Cinder-OpenCV/scons/'

sys.path.append(CINDER_OPENCV_PATH)
import CinderOpenCV
SOURCES += CinderOpenCV.getSources(CINDER_OPENCV_PATH)
INCLUDES += CinderOpenCV.getIncludes(CINDER_OPENCV_PATH)
CVLIBS = CinderOpenCV.getLibs(CINDER_OPENCV_PATH)
LIBS += [File(s) for s in CVLIBS]

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'DEBUG', 'INCLUDES', 'LIBS', 'LIBPATH',
		'ASSETS', 'RESOURCES'])

